name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: Cross Compilation
        run: |
          zig build -Dtarget=x86_64-windows
          zig build -Dtarget=aarch64-linux
          zig build -Dtarget=x86_64-linux
          zig build -Dtarget=aarch64-macos
      - name: Test
        run: zig build test